### ISSUE TITLE
作为依赖加载后报错。

### ISSUE THREAD

**Issue by hevbevt** [lanpangzi-zkg/antd-vite-import-plugin#1]
`failed to load config from /Users/duanhe/demo/main-app/vite.config.ts
error when starting dev server:
/Users/duanhe/demo/main-app/node_modules/antd-vite-import-plugin/antd-vite-import-plugin.js:57
                        map: this?.getCombinedSourcemap(),
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/duanhe/demo/main-app/vite.config.ts:31:49)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.require.extensions.<computed> [as .ts] (/Users/duanhe/demo/main-app/node_modules/vite/dist/node/chunks/dep-66eb515d.js:46332:20)`

js里还有ts的语法。

去掉?后提示'Cannot find module 'param-case'。

思路不错，导出成组件这部分处理一下就能用了。

**Comment by lanpangzi-zkg** [comment]
?.是es2020的Optional Chaining语法，应该是你node版本不兼容的问题，针对这个问题，已经发版做了降级调整，至于找不到param-case的问题，你尝试重新安装试试看
